"""
Pydantic schemas for The Echoing Threshold API.
Defines request/response models for the conversation pipeline.
"""
from typing import Optional, Literal
from pydantic import BaseModel, Field


# ─── Request Models ──────────────────────────────────────────────

class StartSessionRequest(BaseModel):
    character: Literal["bob_dylan_1973"] = "bob_dylan_1973"
    language: str = "en"


class MessageRequest(BaseModel):
    session_id: str
    message: str = Field(..., min_length=1, max_length=2000)
    character: Literal["bob_dylan_1973"] = "bob_dylan_1973"


# ─── Inner Models ────────────────────────────────────────────────

class EmotionAnalysis(BaseModel):
    """Output from Groq emotion analysis."""
    sentiment: Literal["melancholy", "resistance", "hope", "neutral"]
    intensity: float = Field(..., ge=0.0, le=1.0)
    theme_match: Literal["mortality", "farewell", "resistance", "longing", "transcendence"]
    character_response: str
    character: str


class MusicParams(BaseModel):
    """Music parameters generated by Gemini."""
    tempo_bpm: int
    key: str                          # e.g. "Am", "Em", "G"
    instrument_layer: Literal["piano", "harmonika", "ambient_only"]
    rhythm_type: Literal["steady", "arpeggio", "syncopated"] = "steady"
    chord_progression_type: Literal["melancholy", "hope", "resistance", "neutral", "nostalgia", "rage", "peace", "anxiety"] = "neutral"
    reverb_intensity: float = Field(..., ge=0.0, le=1.0)
    historical_soundscape: Literal["radio_static", "crowd_protest", "silence"]
    cross_fade_seconds: float = 3.0


class VisualParams(BaseModel):
    """Visual parameters generated by Gemini."""
    color_palette: Literal["blue_grey", "warm_amber", "stormy_dark", "golden_dusk", "deep_red", "ethereal_white", "sickly_green", "sepia_glow"]
    cloud_density: float = Field(..., ge=0.0, le=1.0)
    door_state: Literal["closed", "ajar", "open"]
    particle_intensity: float = Field(..., ge=0.0, le=1.0)


class HistoricalNote(BaseModel):
    """Historical context note from Gemini."""
    year: int
    event: str
    connection: str  # how it relates to the conversation


# ─── Response Models ─────────────────────────────────────────────

class StartSessionResponse(BaseModel):
    session_id: str
    character: str
    greeting: str
    initial_visual: VisualParams
    initial_music: MusicParams


class ThresholdResponse(BaseModel):
    """Complete response for a conversation turn."""
    session_id: str
    emotion: EmotionAnalysis
    music_params: MusicParams
    visual_params: VisualParams
    historical_note: Optional[HistoricalNote] = None
    turn_count: int


class HealthResponse(BaseModel):
    status: str
    groq_configured: bool
    gemini_configured: bool
    version: str = "2.0.0"
