"""
Pydantic schemas for The Echoing Threshold API.
Defines request/response models for the adaptive conversation pipeline.
"""
from typing import Optional, Literal
from pydantic import BaseModel, Field


CharacterId = Literal[
    "bob_dylan_1973",
    "frontline_soldier",
    "waiting_mother",
    "future_self",
    "the_door",
]

Sentiment = Literal[
    "melancholy",
    "resistance",
    "hope",
    "neutral",
    "nostalgia",
    "rage",
    "peace",
    "anxiety",
    "fear",
    "guilt",
    "violence",
    "longing",
    "grief",
    "tenderness",
    "silence",
    "confusion",
]

ThemeMatch = Literal[
    "mortality",
    "farewell",
    "resistance",
    "longing",
    "transcendence",
    "meaning",
    "identity",
    "threshold",
    "regret",
]


class StartSessionRequest(BaseModel):
    language: str = "en"


class MessageRequest(BaseModel):
    session_id: str
    message: str = Field(..., min_length=1, max_length=2000)
    selected_character: Optional[str] = None


class EmotionAnalysis(BaseModel):
    """Output from Groq emotion analysis."""
    sentiment: Sentiment
    intensity: float = Field(..., ge=0.0, le=1.0)
    theme_match: ThemeMatch
    character_response: str
    character: CharacterId


class MusicParams(BaseModel):
    """Music parameters generated by Gemini."""
    tempo_bpm: int
    key: str
    instrument_layer: Literal["piano", "harmonika", "ambient_only"]
    rhythm_type: Literal["steady", "arpeggio", "syncopated"] = "steady"
    chord_progression_type: Sentiment = "neutral"
    reverb_intensity: float = Field(..., ge=0.0, le=1.0)
    historical_soundscape: Literal["radio_static", "crowd_protest", "silence"]
    cross_fade_seconds: float = 3.0


class VisualParams(BaseModel):
    """Visual parameters generated by Gemini."""
    color_palette: Literal[
        "blue_grey",
        "warm_amber",
        "stormy_dark",
        "golden_dusk",
        "deep_red",
        "ethereal_white",
        "sickly_green",
        "sepia_glow",
        "cold_violet",
        "threshold_gold",
    ]
    cloud_density: float = Field(..., ge=0.0, le=1.0)
    door_state: Literal["closed", "ajar", "open"]
    particle_intensity: float = Field(..., ge=0.0, le=1.0)


class HistoricalNote(BaseModel):
    """Historical context note from Gemini."""
    year: int
    event: str
    connection: str


class StartSessionResponse(BaseModel):
    session_id: str
    character_id: CharacterId
    character_name: str
    greeting: str
    initial_visual: VisualParams
    initial_music: MusicParams


class ThresholdResponse(BaseModel):
    """Complete response for a conversation turn."""
    session_id: str
    character_id: CharacterId
    character_name: str
    character_response: str
    emotion: EmotionAnalysis
    music_params: MusicParams
    visual_params: VisualParams
    historical_note: Optional[HistoricalNote] = None
    turn_count: int


class HealthResponse(BaseModel):
    status: str
    groq_configured: bool
    gemini_configured: bool
    version: str = "2.0.0"
